spring:
  profiles:
    active: dev

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

  mail:
    host: smtp.gmail.com
    port: 587
    username: shshinde@mitaoe.ac.in
    password: nwcx cndq ykoz jwxe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#  kafka:
#    bootstrap-servers: localhost:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.support.serializer.JsonSerializer
#    consumer:
#      group-id: weekly-sentiment-group
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.support.serializer.JsonSerializer
#      properties:
#        spring:
#          json:
#            trusted:
#              packages: com.journalapp.journalApp.model
#    properties:
#      security:
#        protocol: SASL_SSL
#      sasl:
#        mechanism: PLAIN
#        jaas:
#          config: org.spring.kafka.common.security.plain.PlainLoginModule required username='xxx' password='xxxx';
#      session:
#        timeout:
#          ms: 45000

weather:
  api:
    key: dc96263477636586219d1ceeba88e7fb


